name: Jekyll site CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Check out code
        uses: actions/checkout@v2
      - name: âœ”ï¸ Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: ğŸ“¦ Cache NPM packages
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: ğŸ’½ Install NPM packages
        run: npm ci
      - name: ğŸ› ï¸ Compile assets
        run: npm run build --if-present
      - name: ğŸ“¦ Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: ğŸ’½ Install Ruby gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: ğŸš€ Build/Deploy the site
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        env:
          ACCESS_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
